#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cogo.Resource", IsApplication=true)]

namespace Cogo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Background_Cyan = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_bg_Cyan = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_bg_transparent = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_downvote = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_filter_toolbar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_upvote = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int CogoWCircle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int First = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int LoginBackground = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int logo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int OLDIcon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Password1 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int RedButton = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int third = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int two = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int UserName1 = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int Comment = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int DownVote = 2131165191;
			
			// aapt resource value: 0x7f070027
			public const int EPCompanyB = 2131165223;
			
			// aapt resource value: 0x7f070023
			public const int EPDateTimeTxt = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int EPDescriptionTxt = 2131165220;
			
			// aapt resource value: 0x7f07002a
			public const int EPFollowB = 2131165226;
			
			// aapt resource value: 0x7f070028
			public const int EPGoingB = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int EPInterestedB = 2131165225;
			
			// aapt resource value: 0x7f070025
			public const int EPOwnerB = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int EPPhotoB = 2131165222;
			
			// aapt resource value: 0x7f070022
			public const int EPTitleTxt = 2131165218;
			
			// aapt resource value: 0x7f070037
			public const int Emailtxt = 2131165239;
			
			// aapt resource value: 0x7f070016
			public const int ForgotPasswordB = 2131165206;
			
			// aapt resource value: 0x7f07003d
			public const int ImageBirthDate = 2131165245;
			
			// aapt resource value: 0x7f070036
			public const int ImageEmail = 2131165238;
			
			// aapt resource value: 0x7f070034
			public const int ImageName = 2131165236;
			
			// aapt resource value: 0x7f070038
			public const int ImagePassword2 = 2131165240;
			
			// aapt resource value: 0x7f07003a
			public const int ImagePassword3 = 2131165242;
			
			// aapt resource value: 0x7f070035
			public const int Nametxt = 2131165237;
			
			// aapt resource value: 0x7f070014
			public const int Passwordtxt = 2131165204;
			
			// aapt resource value: 0x7f070039
			public const int Passwordtxt2 = 2131165241;
			
			// aapt resource value: 0x7f07003b
			public const int Passwordtxt3 = 2131165243;
			
			// aapt resource value: 0x7f070001
			public const int ProfileImage = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int ReplyButton = 2131165192;
			
			// aapt resource value: 0x7f07001b
			public const int SignInB = 2131165211;
			
			// aapt resource value: 0x7f07003f
			public const int SignInB2 = 2131165247;
			
			// aapt resource value: 0x7f07001f
			public const int SignUpB = 2131165215;
			
			// aapt resource value: 0x7f070041
			public const int SignUpB2 = 2131165249;
			
			// aapt resource value: 0x7f070032
			public const int SignUptxt = 2131165234;
			
			// aapt resource value: 0x7f070006
			public const int UpVote = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int UserName = 2131165187;
			
			// aapt resource value: 0x7f070011
			public const int UserNameTxt = 2131165201;
			
			// aapt resource value: 0x7f07000d
			public const int btn_1 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int btn_2 = 2131165198;
			
			// aapt resource value: 0x7f07003e
			public const int datePicker1 = 2131165246;
			
			// aapt resource value: 0x7f070013
			public const int imagePassword = 2131165203;
			
			// aapt resource value: 0x7f070010
			public const int imageUserName = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int imageView1 = 2131165199;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout1 = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout2 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout3 = 2131165186;
			
			// aapt resource value: 0x7f070015
			public const int linearLayout4 = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout5 = 2131165207;
			
			// aapt resource value: 0x7f07001d
			public const int linearLayout6 = 2131165213;
			
			// aapt resource value: 0x7f07003c
			public const int linearLayout7 = 2131165244;
			
			// aapt resource value: 0x7f07002b
			public const int listView1 = 2131165227;
			
			// aapt resource value: 0x7f070042
			public const int menu_edit = 2131165250;
			
			// aapt resource value: 0x7f070044
			public const int menu_preferences = 2131165252;
			
			// aapt resource value: 0x7f070043
			public const int menu_save = 2131165251;
			
			// aapt resource value: 0x7f070030
			public const int newsDescription = 2131165232;
			
			// aapt resource value: 0x7f07002c
			public const int newsFeedList = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int newsImage = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int newsName = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int newsTime = 2131165231;
			
			// aapt resource value: 0x7f07000c
			public const int password = 2131165196;
			
			// aapt resource value: 0x7f070033
			public const int space1 = 2131165235;
			
			// aapt resource value: 0x7f070031
			public const int space2 = 2131165233;
			
			// aapt resource value: 0x7f07001c
			public const int space3 = 2131165212;
			
			// aapt resource value: 0x7f070020
			public const int space4 = 2131165216;
			
			// aapt resource value: 0x7f070018
			public const int space5 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int space6 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int space7 = 2131165210;
			
			// aapt resource value: 0x7f070012
			public const int space8 = 2131165202;
			
			// aapt resource value: 0x7f070009
			public const int textView1 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int textView2 = 2131165195;
			
			// aapt resource value: 0x7f070021
			public const int toolbar = 2131165217;
			
			// aapt resource value: 0x7f07001e
			public const int txtSignUp = 2131165214;
			
			// aapt resource value: 0x7f070040
			public const int txtSignUp2 = 2131165248;
			
			// aapt resource value: 0x7f07000a
			public const int username = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CommentItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EventDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LoginPage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NewsFeed = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NewsItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RegistrationPage = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int toolbar = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int toolbarmenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int LoginTheme = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int ThemeAppHeader = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int button_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
